name: mystakefriends
description: My Stake Friends - Hearts Knit in Unity
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  
  # State Management
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  image_picker: ^1.0.5
  file_picker: ^6.1.1
  intl: ^0.18.1
  url_launcher: ^6.2.2
  flutter_launcher_icons: ^0.13.1
  
  # Utilities
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  uuid: ^4.2.2
  timeago: ^3.6.0
  flutter_native_splash: ^2.3.5
  
  # Notifications
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon/splash_logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Your logo path
  adaptive_icon_background: "#FFFFFF"  # White background
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"  # Optional

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf